### PR TITLE
Fix zoneinfo install path for packagers, close #4

### LINKED ISSUE #4: Fix zoneinfo install path for packagers
Hi,

to help Linux distribution packagers, you should change this:
```diff
--- a/Makefile.am
+++ b/Makefile.am
@@ -18,7 +18,7 @@

 # Always use $datadir/cyrus-timezones rather than $pkgdatadir,
 # so we can be sure to report the correct path in pkg-config.
-mypkgdatadir = $(datadir)/cyrus-timezones
+mypkgdatadir = $(DESTDIR)/$(datadir)/cyrus-timezones

 install-data-local: zoneinfo
        @echo "Installing zoneinfo in $(mypkgdatadir)"
```

### PR DESCRIPTION
**Pull request by guimard**

### CODE REVIEW

**Review by elliefm — CHANGES_REQUESTED** [review]
Same feedback as I just left on the issue (before seeing the PR): isn't this going to make the path start with `/` if $(DESTDIR) is blank?

I agree with this change in principle but, off the top of my head, I can't remember the correct autotools way to do it safely

**Comment by guimard** [comment]
> Same feedback as I just left on the issue (before seeing the PR): isn't this going to make the path start with `/` if $(DESTDIR) is blank?

It seems that `datadir` starts with a `/`, then we can safely remove the `/`

> I agree with this change in principle but, off the top of my head, I can't remember the correct autotools way to do it safely

**Review by elliefm — APPROVED** [review]

**Comment by elliefm** [comment]
Ah yep, you're right, autoconf's configure enforces that --prefix and friends are always absolute paths.  So the extra '/' was unnecessary but not a problem.  Thanks for tidying it up though. :)

**Comment by guimard** [comment]
Thanks!
What is the benefit of this module in cyrus-imapd ?

**Comment by elliefm** [comment]
I'm not entirely sure!  I _think_ it provides a more thorough set of timezone names than what some platforms provide in their default set?  Which most people won't ever see in practice, but they might turn up in email headers or calendar events from weird clients, so Cyrus needs to know how to interpret them.

@rsto does this sound about right to you?

**Comment by rsto** [comment]
We created cyrus-timezones to have a consistent set of timezones in our test environments and Fastmail production. Before that, timezones could differ due to the libical version and system environments. Other installations might not need cyrus-timezones, if they choose to keep their timezones consistent by other means (or choose not to, at all).

**Comment by guimard** [comment]
I'm packaging Cyrus-Imapd for [Debian](https://www.debian.org), so I need to know if I've to package this or not. I saw in cyrus-imapd that "configure" checks this during build. Then I suppose that if I compile with this module, it becomes a dependency of imapd. Am I right ?

**Comment by elliefm** [comment]
> to have a consistent set of timezones in our test environments and Fastmail production

@rsto Ahh! Do you mean "to have a set of timezones that is consistent between our test environments and Fastmail production", or "to have a consistent set of timezones in our test environments, and a consistent set of timezones in Fastmail production"

In the former case (i.e. "consistency between environments") then Debian et-al would only need to package cyrus-timezones if they were also packaging Cassandane, but otherwise it would be unnecessary.  In the latter case, I guess Debian et-al would need to decide whether to package it based on an assessment of the volatility of the timezone data provided by the system and/or libical packages.

Though there's also [this issue](https://github.com/cyrusimap/cyrus-imapd/issues/2976) open at the moment, which appears when Cyrus is built without cyrus-timezones, but I don't think it's a significant issue in practice (if you're doing something weird, it'll act weird).

**Comment by elliefm** [comment]
> Then I suppose that if I compile with this module, it becomes a dependency of imapd. Am I right ?

To answer that though, yeah, if you package cyrus-timezones and build the cyrus-imapd package with it there, it needs to be a dependency (not just a build-dependency)

**Comment by guimard** [comment]
@elliefm: and I suppose that there is no behavior regression when adding that in the new version

**Comment by elliefm** [comment]
I looked deeper into it, and did find and fix one bug in Cyrus, and added a workaround for libical misbehaving(?) -- details in the issue I linked earlier.  The original issue I thought might exist still might exist, I haven't tested for it specifically yet due to being distracted by the stuff I did fix.

wrt whether or not to packagers should include cyrus-timezones, @rsto mentioned in our chat:
> One thing: using the system timezones is not recommended. If I recall correctly, some of the system timezone definitions defined daylight savings time changes per year, which produced unnecessarily long VTIMEZONEs embedded in the VEVENTs returned by Cyrus.

I have mixed feelings. If, as a mail server admin, you're installing Cyrus from a system package, it seems reasonable to expect it to use the timezone definitions provided by the system.  It also seems reasonable that, if you wish to supply your own timezone definitions instead, that you could configure the `zoneinfo_dir` setting to point to them.

But if, as a package-maintainer, you know your system's timezone definitions are "basic timezone definitions for general purpose use, but perhaps inadequate or suboptimal for building a calendaring service on top of", then it also seems reasonable to package up our cyrus-timezones package and make the cyrus-imapd package depend on it.

**Comment by guimard** [comment]
@elliefm: thank you very much!

**Comment by elliefm** [comment]
(I also think, if you do package up cyrus-timezones and make it a dependency, then you should consider also setting the `zoneinfo_dir` setting explicitly in the default imapd.conf.  It will use it by default if it was built like that, but I think having it explicitly set will be more clear to the admin that it isn't just using the system timezones.)

**Comment by elliefm** [comment]
@guimard FYI I think my advice is going to change again.  I've reverted the "libical workaround" I mentioned (I think it was wrong), and am doing some work to unite both of Cyrus's zoneinfo usages behind the one set of config settings, which should be in beta3 (next week?).

There's also some talk of dropping the cyrus-timezones package, or at least dropping it out of cyruslibs and not presenting it as a "dependency", so I'll keep you advised how that shakes out.

**Comment by guimard** [comment]
OK, if this is the way, I'll drop my request to Debian admin.
Cheers,
Xavier

**Comment by elliefm** [comment]
I've just released 3.2.0-beta3 (announcement email should come through shortly).  It no longer looks for the cyrus-timezones package at build time.  

The timezone directory is now completely controlled by the zoneinfo_dir imapd.conf setting.  If the imapd.conf contains "tzdist" in http_modules, then zoneinfo_dir MUST be set explicitly to a valid zoneinfo directory.  If this module isn't  enabled, then the zoneinfo_dir setting is optional, and the default is to let libical figure it out.

I think my recommendation would be to package cyrus-imapd with the tzdist module not enabled in the default config, and then no special timezone configuration is required either.  As I understand it, the functionality provided by the tzdist module isn't widely supported by calendar client software anyway.

**Comment by guimard** [comment]
@elliefm: thanks a lot for your time! I'll follow your recommendations.

**Pull request merged**
